### ISSUE TITLE
Not nested translations in vanilla

### ISSUE THREAD

**Issue by Justman10000** [PhraseApp-Blog/javascript-l10n-ultimate-guide#5]
@ashour

For example if I use this:

```json
{
    "lang.en": "Englisch"
}
```

works it! But when I use this:

```json
{
    "lang": {
        "en": "English"
    }
}
```

coming *undefined*

**Comment by ashour** [comment]
Hey @Justman10000 👋. The code in the article is really meant as a launch point, not a comprehensive solution. You might be able to develop nested messages without too much hassle using something like [Lodash's _.get() function](https://lodash.com/docs#get).
