### ISSUE TITLE
How to translate custom attributes like text input placeholder?

### ISSUE THREAD

**Issue by pathetix** [PhraseApp-Blog/javascript-l10n-ultimate-guide#6]
Eg: 
`<input type="email" name="email" data-i18n-key="emailPlaceholder" placeholder="john@example.com" />`

Currently it is actually inserting the value of the translation as a value.
(I am using vanilla js fyi)

**Comment by ashour** [comment]
You could use a naming convention like `data-i18n-attr="placeholder" data-i18n-attr-placeholder-key="emailPlaceholder"` and then use `element.setAttribute('placeholder', translation)`.
